all:
	gcc -g ls.c lib.c -o ls
	gcc -g chmod.c  -o chmod 
	gcc -g access.c -o access 
	gcc -g chown.c -o chown 
	gcc -g touch.c -o touch 
	gcc -g stat.c lib.c -o stat 
	gcc -g sh.c lib.c -o sh
clean:
	rm -f ls
	rm -f chmod
	rm -f access
	rm -f chown
	rm -f touch
	rm -f stat
	rm -f sh
