all:
	gcc -g ls.c  -o ls
	gcc -g chmod.c  -o chmod 
	gcc -g access.c -o access 
	gcc -g chown.c -o chown 
	gcc -g touch.c -o touch 
clean:
	rm -f ls
	rm -f chmod
	rm -f access
	rm -f chown
	rm -f touch
